packages:
  - docs
  - bindings/ts/core
  - bindings/ts/node
  - bindings/ts/node/npm/*
  - bindings/ts/react-native
  - bindings/ts/react-native/example
  - bindings/ts/test-fixtures

allowBuilds:
  "@scarf/scarf": true
  esbuild: true

catalog:
  "@types/node": 26.4.1
  "@types/react": 19.2.18
  del-cli: 7.0.0
  react: 19.2.8
  react-native: 0.86.2
  typescript: 7.0.2

minimumReleaseAgeExclude:
  - blume@1.6.3
  - katex@0.18.6
  - "@expo/cli@56.1.22"
  - "@expo/inline-modules@0.0.15"
  - "@expo/local-build-cache-provider@56.0.11"
  - expo@56.0.18
  - "@turbo/darwin-64@2.10.12"
  - "@turbo/darwin-arm64@2.10.12"
  - "@turbo/linux-64@2.10.12"
  - "@turbo/linux-arm64@2.10.12"
  - "@turbo/windows-64@2.10.12"
  - "@turbo/windows-arm64@2.10.12"
  - turbo@2.10.12
  - ultracite@7.11.0

nodeLinker: hoisted

saveExact: true

patchedDependencies:
  uniffi-bindgen-react-native@0.31.0-5: bindings/ts/react-native/patches/uniffi-bindgen-react-native@0.31.0-5.patch
